services:
  - type: web
    name: netcurea-app
    env: python
    buildCommand: pip install Flask flask-cors pymongo bcrypt python-dotenv
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
